import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header"
import BottomNav from "../components/BottomNav"
import ChapterSidebar from "../components/ChapterSidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const chapters = []
  try {
    // load minimal chapter metadata for header drawer
    // eslint-disable-next-line no-undef
    const g = require('../lib/gita.json')
    chapters.push(...(g.chapters || []))
  } catch (e) { }

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body className="min-h-full flex flex-col">
        <Header chapters={chapters} />
        <main className="flex-1 max-w-4xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="sm:grid sm:grid-cols-4 sm:gap-6">
            <aside className="hidden sm:block sm:col-span-1">
              <div className="sticky top-6 space-y-2">
                <ChapterSidebar chapters={chapters} />
              </div>
            </aside>
            <section className="sm:col-span-3">
              {children}
            </section>
          </div>
        </main>
        <BottomNav />
      </body>
    </html>
  )
}
